[package]
name = "elise-gc"
edition = "2021"
version = "0.1.0"
description = "Raw GC of Für Elise"
license = "Apache-2.0 OR MIT"

[lib]
path = "lib.rs"

[dependencies]
crossbeam = "0.8"
dashmap = "5.3"
log = "0.4.5"
once_cell = "1.12"
pin-cell = "0.1.1"
